[package]
name = "amin"
version = "0.1.0"
edition = "2021"
description = "Robust job processing in Rust, backed by modern PostgreSQL and SQLite3"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
